### ISSUE TITLE
[BUG] Copilot SDK同梱runtimeの完全一致バージョン固定により更新後のruntimeをadmitできない

### ISSUE THREAD

**Issue by fukuda-yuki** [fukuda-yuki/local-agent-monitor#173]
## 現在起きている問題

Issue #158 の Group 5 と compatibility registry は、`GitHub.Copilot.SDK` 1.0.4 が起動する application-bundled Copilot CLI runtime について、same-client status `1.0.65` の完全一致を要求している。

現在の application-bundled runtime は `1.0.75` を自己申告しているため、この条件に一致せず runtime generation が admit されない。その結果、Skill の live producer、handoff、writer は inactive のままとなっている。

runtime version を単一の固定値へ拘束したままでは、今後 runtime がバージョンアップした場合も、固定値と一致しないことを理由に利用できなくなる。

## 要望

runtime version を単一の固定値として扱わない。

期待する runtime version は指定できるようにした上で、実際の runtime version は可変として扱いたい。

今後の runtime version の更新に追随できる契約にしたい。

---

# Implementation Plan (v3, revised 2026-08-22 after second independent review)

Everything above this rule is the Product Owner's original statement and is
reproduced unchanged.

Plan history: v1 recommended a declared version **range**. Review 1 rejected
that and found the revision-2 diagnostic defect; v2 flipped to an **exact
accepted tuple set** and restructured the tasks. Review 2 confirmed the core
design and returned five implementation-blocking gaps, all verified against the
code and accepted here.

## 0. What changed in v3

| Review 2 finding | Verdict | v3 |
|---|---|---|
| 1 — T0a is not independent of the SDK configuration blocker | **Accepted** | T0a/T0b both require test-scoped persistence config; T0b's session requirements enumerated |
| 2 — T0a/T0b could be satisfied by two different clients | **Accepted** | T0b now carries the complete same-client chain; T0a demoted to characterization |
| 3 — `COPILOT_CLI_PATH` can substitute an external runtime | **Accepted (new Decision H)** | Fail closed on any ambient value; this risk becomes live *because of* this change |
| 4 — "r0003 needs no code change" is false | **Accepted** | Decision B wording corrected; the loader's per-revision constants are hard-coded |
| 5 — an internal companion leaves a public API that cannot be satisfied | **Accepted (new Decision I)** | Full internalization is viable: there are zero consumers outside this assembly |
| Fingerprint wording | Accepted | T0b split into artifact proof and runtime-compatibility proof |
| MonitorHost must not activate | Accepted, **with a correction** | See below — the gateway *is* already composed |
| Registry-owned revision type | Accepted | New neutral type; `Entries` replaced, not aliased |
| "Decisions A–F" | Accepted | Typo; the set is A–I |

### Correction to Review 2

Review 2 states the host "does not register the gateway or construct
`CopilotSdkBundleClientV1`". That is not accurate. `MonitorHost.cs:2058`
**does** compose `CopilotSdkSkillDiscoveryGateway` with
`static () => new CopilotSdkBundleClientV1()`, gated on a non-null root
generation and runtime admission. The accurate statement, verified:

```text
- the client factory is deferred; no client is constructed at composition time
- AdmitRuntimeGenerationAsync has NO production caller (tests only)
- therefore no generation is ever admitted in production today
```

This matters twice: T4's `MonitorHost` work is at **`:2058`** as well as
`:226,233`, and #173 alone cannot be verified by running the host — only by
tests plus the T0 harness. See R5.

### Verification status of SDK-internal claims

The `GitHub.Copilot.SDK` package is not restored in this environment, so two
Review 2 claims could **not** be verified directly and are recorded as T0
preconditions to confirm, not as established facts:

- that the `CopilotClient` constructor throws for `Mode == Empty` without
  `BaseDirectory`/`SessionFs` (corroborated by `docs/task.md`, which already
  records this requirement as a #158 blocker);
- the runtime resolution order that gives `COPILOT_CLI_PATH` precedence over
  the bundled runtime.

Decision H's guard is required regardless of the second claim's exact form,
because the specification independently forbids `COPILOT_CLI_PATH` substitution.

What **was** verified: `BundleClientWrapper_ConstructsHeadlessEmptyModeOptionsOnly`
(`CopilotSdkSkillDiscoveryGatewayTests.cs:333-345`) injects a factory returning
`null!`, so it never invokes the real constructor and proves nothing about
client constructibility.

### 1a. Literal inventory (where `1.0.65` is hard-coded)

| # | Location | Role |
|---|---|---|
| 1 | `SkillRuntime/CopilotRuntimeGenerationV1.cs:84` | `AdmittedCopilotVersion`; `:98` assigns it to `FrozenVersion` instead of the observed status |
| 2 | `SkillRuntime/CopilotSdkSkillDiscoveryGateway.cs:168-174` | `CertifiesAdmission` compares `status.Version` to the constant |
| 3 | `Sessions/SkillInvocationV2/SkillInvocationNormalizedJsonV1.cs:14,102,223` | producer writes the literal to the wire |
| 4 | `Sessions/SkillInvocationV2/SkillInvocationV2Parser.cs:12,146` | `RequireExactString` against the constant |
| 5 | `SkillInvocationV2IngestRequestFactsV1.cs:37,56`, `SkillInvocationV2IngestTransactionV1.cs:316` | producer tuple, receipt field 12, persisted column |
| 6 | `docs/.../compatibility-registry-r0001.json` | sole entry; byte-frozen (431 bytes, `3ae5d255…`); loader fails unless `registryHistory.Count == 1` |

### 1b. Change surface (files with no literal that must still change)

| Location | Why |
|---|---|
| `CopilotRuntimeAdmissionV1.cs` | `PublishAdmittedGeneration` calls `new CopilotRuntimeGenerationV1(client)`; the certifying status never reaches the generation |
| `SkillRuntimeCapabilityBridgeV1.cs:128` | `TryWriteCancellable(nativeSessionId, sourceEvent, workToken, out body)` passes no identity |
| `SkillInvocationV2Contracts.cs` — `ParsedSkillInvocationV2Batch` | the parser validates the version and then **discards** it |
| `SkillInvocationV2IngestTransactionV1.cs:316` | passes the parser constant into `SessionSkillInvocationWrite` |
| `MonitorHost.cs:226,233` **and `:2058`** | registry provider and runtime admission built separately; the gateway is composed at `:2058` and needs the shared registry |

### 1c. Already version-agnostic

- `skill-invocation-snapshot.schema.v1.sql:74` — `TEXT NOT NULL CHECK(length(...)>0)`.
- 29-field receipt frame — version is data (field 12).
- `metadata-response-v1.golden.json` — same.
- `ReportSessionStartObservationAsync:158` — already compares to `FrozenVersion`.
- `ParseRegistry` (`:176-179`) validates `schema_version == "skill-sdk-compatibility-registry.v1"` and `registry_revision`. **Revision 2 reuses the v1 entry shape**; no `…registry.v2` schema.

## 2. The two invariants — and why they are not sufficient alone

```text
Invariant 1 (agreement)
  actual same-client producer status
    == capability-bound emitted source_application_version

Invariant 2 (certification)
  the complete emitted producer tuple
    is accepted by the greatest complete current registry revision

Invariant 3 (origin)   <- added in v3
  the certified producer is the application-co-located bundled runtime,
  not an external runtime selected by environment or explicit path
```

Invariant 3 is not redundant. Once r0002 accepts `1.0.75`, an external or global
CLI reporting `1.0.75` satisfies invariants 1 and 2 exactly while being the
wrong producer. Today that is masked only because nothing is admitted at all.

## 3. Scope / non-scope

**In scope:** how the admitted runtime version is declared, certified, carried,
persisted, and how the bundled origin is enforced.

**Not in scope:** SDK `1.0.4 / 1.0.4.0`, `adapter_version`,
`normalization_version`, `payload_schema`, `schema_fingerprint`; frozen ingest
v1; v2 route bytes, status/error precedence, terminal ordering, Retention/#154;
receipt frame; SQLite schema; **and the other two #158 live-producer blockers**
(the `CopilotClientMode.Empty` production configuration, and side-effect-free
attach to a foreign session). **Closing #173 does not activate the live
producer.**

## 4. Product Owner decisions (blocking)

D083 and Group 5 are decision-closed and pin exact `1.0.65`. Per `AGENTS.md`
this conflict is stated before editing.

### Decision A — expectation authority

```text
The sole authority for the expected source_application_version is the greatest
complete compatibility-registry revision embedded in the running application.
argv, environment variables, appsettings, user configuration, PATH, file
metadata, and the global CLI are never admission authority.
```

### Decision B — matching policy

- **(i) Exact accepted tuple set — recommended.** Admission is ordinal string
  equality against the current revision's accepted entries.
- **(ii) Declared range — available, not recommended.** The only option that
  follows a CLI update with zero repository change, which may be what
  "追随できる契約" means to the PO. Cost: the specification says *"A later CLI
  or SDK requires a new complete immutable registry revision plus producer/live
  certification"*, and a range deliberately overrides that; it also forces
  version-ordering, prerelease/build-label, and overlapping-range decisions the
  exact set does not need.

**Accurate statement of what (i) costs per future CLI** *(v2 overstated this;
review 2 finding 4)* — the loader hard-codes `RegistryR0001ResourceName`,
`RegistryR0001Fingerprint`, `RegistryR0001ByteLength`, the embedded history
dictionary, and `registryHistory.Count == 1`, and both csproj files enumerate
the artifact individually. So r0003 requires:

```text
Required per future CLI under (i):
- one new immutable registry artifact
- certification evidence (a T0-equivalent run)
- mechanical inventory updates: csproj entry, resource-name/hash/length
  constants, the history dictionary, and the artifact tests

NOT required:
- any change to the admission algorithm, wire schema, persistence schema,
  receipt format, or diagnostic semantics
```

That is still categorically different from today, where each update means
re-embedding the literal in admission, writer, and parser. A wildcard
`compatibility-registry-rNNNN.json` loader would make it truly artifact-only,
but it is **not** required to solve #173 and is left out of scope.

### Decision C — r0002 contents

After T0 succeeds: `registry_revision = 2`, `schema_version` unchanged,
`1.0.65 -> accepted`, `1.0.75 -> accepted`. r0001 byte-identical forever.

### Decision D — protocol

`ProtocolVersion == 3` exact. Frozen on the generation; never added to wire,
receipt, DB, backup, log, or metric.

### Decision E — runtime generation binding

The generation immutably freezes observed `Version`, observed
`ProtocolVersion`, the accepted complete tuple, and the accepting
`RegistryRevision`. A `SessionStart` version that does not exactly match the
frozen observed version invalidates the generation.

### Decision F — registry lifetime

No production hot reload. The complete embedded history loads once at startup;
the greatest complete revision is the current authority for the process
lifetime. Revision updates ship with an application update or restart.

### Decision H — bundled runtime selection *(new; review 2 finding 3)*

```text
Production certification fails closed when the current process carries any
COPILOT_CLI_PATH value, including an empty-but-present one.
The client supplies no explicit RuntimeConnection path or URI.
With no explicit path and no COPILOT_CLI_PATH, the SDK-owned bundled-runtime
resolution is the only permitted selection path.
The variable's value and any runtime path are never logged, persisted,
returned, fingerprinted, or measured.
```

Decision A alone is insufficient: it stops the environment being *admission*
authority, while this stops it being *runtime selection* authority.

### Decision I — capability surface visibility *(new; review 2 finding 5)*

`ISkillInvocationV2RuntimeCapability`, `SkillInvocationV2Parser`, and
`ParsedSkillInvocationV2Batch` are all `public`. Adding a member only to an
internal companion would leave a public `Parse` that external callers can bind
to but never satisfy. Choose **before** T5, not during it:

- **(A) Public contract** — widen the marker interface and make the identity
  type public too.
- **(B) Full internalization — recommended.** Internalize the interface,
  parser, `Parse`, the batch, and the capability-bearing handoff members
  together.

Evidence for (B): no code outside `CopilotAgentObservability.LocalMonitor`
references any of these three types, and `InternalsVisibleTo` already covers
`…LocalMonitor.Tests` and `…Doctor.Tests`. Nothing outside the assembly loses
access.

### Decision G — r0001 tuple disposition

`1.0.65` stays **accepted** in r0002, so existing rows keep reporting
`current`. Revoke only on a concrete incompatibility, which correctly yields
`stale`. No global carry-forward invariant is needed.

## 5. Design

```text
guard            no COPILOT_CLI_PATH, no explicit path/URI  (Decision H)
admission        observed status -> candidate complete tuple
                 -> exact match against current revision accepted entries
                 -> CertifiedSkillProducerIdentityV1 frozen on the generation
capability       carries that identity, not a bare version string
writer           emits the identity's tuple
parser           requires the envelope tuple to equal the capability's identity
facts/receipt    carry the accepted tuple; field 12 is the accepted version
persistence      SessionSkillInvocationWrite reads facts, not a static constant
diagnostic       exact tuple lookup over the full immutable history
```

```csharp
internal sealed record CertifiedSkillProducerIdentityV1(
    string SourceApplicationVersion,
    int ProtocolVersion,
    string AdapterVersion,
    string NormalizationVersion,
    string PayloadSchema,
    string SchemaFingerprint,
    int RegistryRevision);

// registry-owned, consumed by the diagnostic (v3: no longer the diagnostic's type)
public sealed record SkillInvocationV2CompatibilityRegistryRevision(
    int Revision,
    IReadOnlyList<SkillInvocationV2CompatibilityRegistryEntry> Entries);
```

### The revision-2 diagnostic defect (still the highest-risk item)

`SkillProjectionDiagnosticV1.Diagnose(bool, tuple)` builds a one-element history
from `CurrentRevision` + `Entries`, and `TryValidateHistory` requires index 0 to
declare revision 1. `SkillProjectionDiagnosticV1Tests.cs:69`
(`Diagnose_HistoryStartingAtRevisionTwoIsUnavailable`) pins it. Setting
`CurrentRevision = 2` alone makes **every live snapshot diagnostic return
`unavailable`**. The registry must expose:

```csharp
public IReadOnlyList<SkillInvocationV2CompatibilityRegistryRevision> History { get; }
public IReadOnlyList<SkillInvocationV2CompatibilityRegistryEntry> CurrentEntries { get; }
```

Admission reads `CurrentEntries` only; the diagnostic reads `History`; a lower
revision is never an admission fallback. Both are defensive copies. The old
`Entries` property is **replaced**, not kept as an alias — this contract is
unreleased, so two current-entry properties would be pure ambiguity.

### T0 — certification evidence *(gate)*

Preconditions to record for both halves:

```text
COPILOT_CLI_PATH absent
no explicit RuntimeConnection path or URI
test-scoped BaseDirectory or SessionFs        (SDK 1.0.4 Empty-mode requirement)
```

- **T0a — preliminary characterization.** Confirm `1.0.75` and protocol `3` are
  observable, and confirm the two unverified SDK claims above. **T0a alone does
  not certify r0002.**
- **T0b — the complete same-client chain** *(review 2 finding 2)*. All steps on
  **one** `CopilotClient`:

```text
1. client.StartAsync
2. GetStatusAsync on that same client
3. Version == 1.0.75
4. ProtocolVersion == 3
5. create a test-owned Session on that same client
6. SessionStartData.CopilotVersion == 1.0.75
7. observe a SkillInvokedEvent from that Session
8. run it through the existing mapper / normalized writer / parser
```

  Session configuration required by SDK 1.0.4, all test scope only:

```text
BaseDirectory or SessionFs
AvailableTools        exact nonnull allowlist
EnableSkills          true (default is false)
SkillDirectories      synthetic temporary Skill directory
OnEvent               registered before Session creation
```

  Acceptance, split *(the fingerprint is the schema artifact's digest, not the
  event's)*:

```text
Artifact proof:
  schema bytes remain exactly 980 bytes; SHA-256 remains 8fac48d8...
Runtime compatibility proof:
  the same-client 1.0.75 SkillInvokedEvent maps through the existing typed
  mapper; normalized output is accepted by the existing parser/schema
  contract; supplied optional values keep their expected semantics
```

  One live event cannot exercise every optional member; combine it with the
  existing synthetic exhaustive mapper tests.

  Use a temporary directory and a synthetic non-sensitive Skill. No real user
  session, no foreign-session attach. The test-scoped configuration is evidence
  scaffolding and **does not** decide or resolve #158's production composition
  blocker.

**If T0b fails, `1.0.75` must not be added to r0002 as accepted, and T1–T8 do
not start.**

### T1 — decisions and specifications

Files: `docs/decisions.md`, `docs/specifications/interfaces/skill-invocation-snapshot.md`, `docs/specifications/layers/telemetry-ingestion.md`, `docs/specifications/layers/skill-projection.md`, `docs/requirements.md`.

```text
- r0001's historical identity, bytes, hash, and exact 1.0.65 prose unchanged
- current admission no longer depends on a compile-time literal
- the expected value comes from the current revision's accepted exact tuples
- the observed status version is emitted as the capability-bound tuple
- bundled-origin enforcement (Decision H) is specified
- D083's body is not edited; a new decision supersedes only its Group 5
  current-version clause
```

A stale search for `1.0.65` must **not** target zero hits.

### T2 — r0002 artifact

Add the artifact, register it in both csproj files, pin its byte length and
SHA-256, keep r0001 byte-identical.

### T3 — registry loader and full history

`SkillInvocationV2ArtifactRegistry.cs` + its own tests: independent byte
verification of r0001 and r0002; history exactly `{1,2}` and contiguous;
`History`/`CurrentEntries` separated; admission sees revision 2 only; a
malformed r0002 never falls back to r0001; duplicate tuples and unproven
revokes rejected. *(v2 mis-cited T7 here.)*

### T4 — runtime certification, origin guard, and generation

Files: `CopilotSdkSkillDiscoveryGateway.cs`, `CopilotRuntimeAdmissionV1.cs`, `CopilotRuntimeGenerationV1.cs`, `MonitorHost.cs` (`:226,233` **and `:2058`**), runtime test doubles.

Origin guard tests:

```text
COPILOT_CLI_PATH absent        -> construction may proceed
COPILOT_CLI_PATH nonempty      -> no client constructed, no generation admitted
COPILOT_CLI_PATH empty-present -> fail closed, not treated as absent
no explicit RuntimeConnection or URI
```

Certification: candidate tuple from observed status; exact match against
current entries; certified identity passed through `PublishAdmittedGeneration`
into the generation constructor; `FrozenVersion` is the observed version;
protocol exact `3`; SessionStart drift invalidates.

`MonitorHost` scope fence — #173 changes composition only:

```text
- one startup-loaded registry instance is shared with the gateway at :2058
- no eager CopilotSdkBundleClientV1 construction (the factory stays deferred)
- no gateway hosted-service registration
- no AdmitRuntimeGenerationAsync production caller
- no callback subscription, Session creation, or attach
- no producer activation
```

### T5 — capability-bound writer and parser

Files: `SkillInvocationV2Contracts.cs`, `SkillRuntimeCapabilityBridgeV1.cs`, `SkillInvocationNormalizedJsonV1.cs`, `SkillInvocationV2Parser.cs`. Decision I is already settled at this point.

### T6 — facts, receipt, persistence

Files: `ParsedSkillInvocationV2Batch`, `SkillInvocationV2IngestRequestFactsV1.cs`, `SkillInvocationV2IngestTransactionV1.cs`. Prove `1.0.65` and `1.0.75` produce different receipt fingerprints.

### T7 — diagnostic

Full contiguous history; both versions `current` under r0002; only an explicit
revoke yields `stale`; absent tuple stays `invalid`; malformed or gapped
history stays `unavailable`; no lower-revision fallback.

### T8 — regression, goldens, full validation

726-byte receipt golden unchanged; metadata golden's `1.0.65` unchanged as
fixture data; r0001 bytes/hash unchanged; positive `1.0.75` vector;
generation/envelope mismatch, SessionStart drift, unknown `1.0.76` rejection,
protocol mismatch, and the three `COPILOT_CLI_PATH` cases; full repository
validation; `docs/task.md` (≈L131) records blocker 1 resolved with the other
two intact.

## 7. Risks

- **R1 — artifact immutability.** r0001 byte-identical. Guarded by T2/T3.
- **R2 — historical rows.** Guarded by Decision G and T7.
- **R3 — the revision-2 diagnostic defect.** Pinned by an existing test; would silently degrade every live diagnostic. Guarded by T3.
- **R4 — shape drift.** Guarded by T0b running before r0002 is written.
- **R5 — scope drift, two ways.** A passing admission gate reads as "the live producer works"; it does not, and with no production caller for `AdmitRuntimeGenerationAsync` the change is not even observable by running the host. Separately, T0's test-scoped SDK configuration must not be mistaken for resolving #158's production composition blocker.
- **R6 — visibility.** Settled by Decision I before T5.
- **R7 — external runtime substitution.** New in v3, and live precisely because r0002 accepts the version an external CLI also reports. Guarded by Decision H and T4.

## 8. Definition of done

1. T0b's complete same-client chain recorded (T0a is supplementary only);
   Decisions A–I ratified.
2. r0002 added additively with exact accepted tuples; r0001 byte-frozen.
3. Registry exposes full history and current entries separately; the diagnostic
   still works at revision 2.
4. Admission enforces bundled origin and resolves the version from one
   certified identity rather than a static constant, end to end.
5. Full validation green; byte-pinned goldens unchanged.
6. `docs/task.md` records exactly one of the three #158 producer blockers as
   resolved.

**Comment by fukuda-yuki** [comment]
Completed by PR #172.

- Candidate: `23ec5f70a19d23ce4bba1ed28583f7722aeb13f7`
- Merge commit: `91bc60015f229a16b9d5973d57953f1ad03e5790`
- Evidence: `docs/sprints/issue-158-skill-invocation-snapshot/milestones/M1-owned-session-producer/live-validation.md`
- Acceptance delivered: exact 1.0.65/1.0.75 protocol-3 admission, contiguous r0001/r0002 history, immutable certified producer identity, writer/parser/facts/transaction/persistence propagation, wire-field capability checks, environment override guard, and runtime internalization.
- Frozen validation: 13,979 passed / 4 expected skipped / 0 failed; build completed with 0 errors.
- Fresh identity/persistence review at the candidate: Critical 0 / Integral 0 / Minor 0.
